Remove hardcoded variables and add their declaration to YAML configuration file
wazo-platform/wazo-webhookd pull request #135
Opened 2022-04-07 15:25 UTC by nissou91

2022-04-08 08:47 UTC, sduthil requested changes
You just removed an essential part of the push notification: push notifications *absolutely need* a key `apns-topic` in order to work.

You need to make `apns-topic` configurable, by reading the value from the config file.

2022-04-08 15:32 UTC, pc-m requested changes

2022-04-08 15:32 UTC, pc-m commented on wazo_webhookd/services/mobile/plugin.py
> +                'apns-topic': apns_topic_value,
This one should use the `mobile_apns_default_topic` since it used `mobile_apns_default_topic` before

2022-04-08 15:32 UTC, pc-m commented on wazo_webhookd/services/mobile/plugin.py
> +                'apns-topic': apns_topic_value,
This one should use the `mobile_apns_default_topic` since it used `mobile_apns_default_topic` before

2022-04-11 16:17 UTC, sduthil requested changes

2022-04-11 16:17 UTC, sduthil commented on wazo_webhookd/services/mobile/plugin.py
> +        apns_topic_value = self.config['mobile_apns_call_topic']
It is not clear what is the difference between `apns_topic_value` and `apns_default_topic_value`. Please rename `apns_topic_value` to something like `apns_call_topic`.
You can also drop the `_value` in variable names, I don't think they bring anything.

2022-04-11 17:11 UTC, merged