Wazo 2769 firebase proxy
wazo-platform/wazo-webhookd pull request #142
Opened 2022-08-11 18:20 UTC by pc-m

2022-08-16 15:03 UTC, sduthil requested changes

2022-08-16 15:03 UTC, sduthil commented on etc/wazo-webhookd/config.yml
> +mobile_fcm_notification_send_jwt_token: false  # Sends the Wazo JWT token instead of the fcm API key (should be true when using a FCM proxy)
We should make this more flexible... I'm thinking of something like:
```
mobile_fcm_notification_auth_reference: metadata/my_key
```

2022-08-19 16:02 UTC, pc-m commented on integration_tests/suite/test_mobile_callback.py
> +        )
Yeah, I'm lazy and copied other tests

2022-08-22 12:24 UTC, pc-m commented on integration_tests/suite/test_mobile_callback.py
> +                    'body': {
You're right, I added a verify to the test

2022-08-24 14:07 UTC, sduthil approved these changes

2022-08-24 14:08 UTC, merged